export type Serie = typeof serie;

export const serie = {
  originalSeries: "Original Series",
  neoSeries: "Neo Series",
  legendaryCollectionSeries: "Legendary Collection Series",
  eCardSeries: "E-Card Series",
  exSeries: "EX Series",
  diamondPearlSeries: "Diamond & Pearl Series",
  platinumSeries: "Platinum Series",
  heartGoldSoulSilverSeries: "HeartGold & SoulSilver Series",
  callOfLegendsSeries: "Call of Legends Series",
  blackWhiteSeries: "Black & White Series",
  xySeries: "XY Series",
  sunMoonSeries: "Sun & Moon Series",
  swordShieldSeries: "Sword & Shield Series",
  scarletVioletSeries: "Scarlet & Violet Series",
  megaEvolutionSeries: "Mega Evolution Series",
  mcDonaldsSeries: "McDonald's Series",
  trickOrTrade: "Trick or Trade",
  basicEnergyCards: "Basic Energy Cards",
  promotionalSeries: "Promotional Series",
  blackStarPromotionalCards: "Black Star Promotional Cards",
  popSeries: "POP Series",
};
